#include "unity.h"
#include "test_hooks.h"
#include "../../SerialHandler/include/SerialHandler.h"
#include "RadioManager.h"
#include "CATHandler.h"
#include "ParserUtils.h"
#include "CommandDispatcher.h"
#include "FrequencyVfoCommandHandler.h"
#include "ModeCommandHandler.h"
#include "ReceiverProcessingCommandHandler.h"
#include "InterfaceSystemCommandHandler.h"
#include "StatusInfoCommandHandler.h"
#include "TransmitterCommandHandler.h"
#include "GainLevelCommandHandler.h"
#include "AntennaCommandHandler.h"
#include "CwCommandHandler.h"
#include "MemoryCommandHandler.h"
#include "ScanCommandHandler.h"
#include "ToneSquelchCommandHandler.h"
#include "AudioEqualizerCommandHandler.h"
#include "VisualScanCommandHandler.h"
#include "MenuConfigCommandHandler.h"
#include "VoiceMessageCommandHandler.h"
#include "../../SerialHandler/mock/include/MockSerialHandler.h"
#include "esp_log.h"

namespace radio {

// Test fixture
static std::unique_ptr<MockSerialHandler> mockRadioSerial;
static std::unique_ptr<MockSerialHandler> mockUsbSerial;
static RadioManager* radioManager;
static CommandDispatcher* commandDispatcher;
static CATHandler* radioCatHandler;

// Using separate setup/teardown to avoid conflicts with other test files
void setUp_RadioCATHandler() {
    mockRadioSerial = std::make_unique<MockSerialHandler>();
    mockUsbSerial = std::make_unique<MockSerialHandler>();

    radioManager = new RadioManager(*mockRadioSerial, *mockUsbSerial);
    
    commandDispatcher = new CommandDispatcher();
    
    // Register command handlers needed for tests
    auto frequencyHandler = std::make_unique<FrequencyVfoCommandHandler>();
    auto modeHandler = std::make_unique<ModeCommandHandler>();
    auto receiverProcessingHandler = std::make_unique<ReceiverProcessingCommandHandler>();
    auto statusInfoHandler = std::make_unique<StatusInfoCommandHandler>();
    auto interfaceSystemHandler = std::make_unique<InterfaceSystemCommandHandler>();
    auto transmitterHandler = std::make_unique<TransmitterCommandHandler>();
    auto gainLevelHandler = std::make_unique<GainLevelCommandHandler>();
    auto antennaHandler = std::make_unique<AntennaCommandHandler>();
    auto cwHandler = std::make_unique<CwCommandHandler>();
    auto memoryHandler = std::make_unique<MemoryCommandHandler>();
    auto scanHandler = std::make_unique<ScanCommandHandler>();
    auto toneSquelchHandler = std::make_unique<ToneSquelchCommandHandler>();
    auto audioEqualizerHandler = std::make_unique<AudioEqualizerCommandHandler>();
    auto visualScanHandler = std::make_unique<VisualScanCommandHandler>();
    auto menuConfigHandler = std::make_unique<MenuConfigCommandHandler>();
    auto voiceMessageHandler = std::make_unique<VoiceMessageCommandHandler>();
    
    commandDispatcher->registerHandler(std::move(frequencyHandler));
    commandDispatcher->registerHandler(std::move(modeHandler));
    commandDispatcher->registerHandler(std::move(receiverProcessingHandler));
    commandDispatcher->registerHandler(std::move(statusInfoHandler));
    commandDispatcher->registerHandler(std::move(interfaceSystemHandler));
    commandDispatcher->registerHandler(std::move(transmitterHandler));
    commandDispatcher->registerHandler(std::move(gainLevelHandler));
    commandDispatcher->registerHandler(std::move(antennaHandler));
    commandDispatcher->registerHandler(std::move(cwHandler));
    commandDispatcher->registerHandler(std::move(memoryHandler));
    commandDispatcher->registerHandler(std::move(scanHandler));
    commandDispatcher->registerHandler(std::move(toneSquelchHandler));
    commandDispatcher->registerHandler(std::move(audioEqualizerHandler));
    commandDispatcher->registerHandler(std::move(visualScanHandler));
    commandDispatcher->registerHandler(std::move(menuConfigHandler));
    commandDispatcher->registerHandler(std::move(voiceMessageHandler));
    
    radioCatHandler = new CATHandler(*commandDispatcher, *radioManager,
        *mockRadioSerial, *mockUsbSerial, CommandSource::Remote);

    radioManager->setRadioConnected(true);
}

void tearDown_RadioCATHandler() {
    delete radioCatHandler;
    delete commandDispatcher;
    delete radioManager;
    mockRadioSerial.reset();
    mockUsbSerial.reset();
}

// --- Test Cases ---

void test_radioCATHandler_parseRemoteResponse_FA() {
    setUp_RadioCATHandler();
    
    // Simulate the radio sending a frequency update
    radioCatHandler->parseMessage("FA00014074000;");
    
    // Process the event generated by the handler
    
    // Assert that the state was updated correctly
    TEST_ASSERT_EQUAL_UINT32(14074000, static_cast<uint32_t>(radioManager->getState().vfoAFrequency.load()));
    
    tearDown_RadioCATHandler();
}

void test_radioCATHandler_parseRemoteResponse_MD() {
    setUp_RadioCATHandler();
    
    // Simulate the radio sending a mode update
    radioCatHandler->parseMessage("MD4;");
    
    // Process the event
    
    // Assert the state change
    TEST_ASSERT_EQUAL(4, radioManager->getState().mode.load());
    
    tearDown_RadioCATHandler();
}

void test_radioCATHandler_parseRemoteResponse_IF() {
    setUp_RadioCATHandler();
    
    // Use the helper to create a realistic IF response with specific values
    const std::string full_if_response = cat::ParserUtils::buildIFResponse(
        14074000,     // VFO A frequency
        100,          // RIT/XIT offset  
        true,         // RIT on
        true,         // XIT on
        5,            // Memory channel 5
        true,         // TX on
        4,            // Mode 4: FM
        true,         // Split on
        0,            // Tone disabled
        0             // Tone number
    );
    
    // For backwards compatibility with the old fixed string test, also validate that format
    // const char* full_if_response = "IF00014074000xxxxx 01001100514xx1;";

    radioCatHandler->parseMessage(full_if_response.c_str());

    TEST_ASSERT_EQUAL_UINT32(14074000, static_cast<uint32_t>(radioManager->getState().vfoAFrequency.load()));
    TEST_ASSERT_EQUAL(100, radioManager->getState().ritXitOffset.load());
    TEST_ASSERT_TRUE(radioManager->getState().ritOn.load());
    TEST_ASSERT_TRUE(radioManager->getState().xitOn.load());
    TEST_ASSERT_EQUAL(5, radioManager->getState().memoryChannel.load());
    TEST_ASSERT_TRUE(radioManager->getState().isTx.load());
    TEST_ASSERT_EQUAL(4, radioManager->getState().mode.load());
    TEST_ASSERT_TRUE(radioManager->getState().split.load());

    tearDown_RadioCATHandler();
}

// Test for VS (Visual Scan) command parsing
void test_radioCATHandler_parseRemoteResponse_VS() {
    setUp_RadioCATHandler();
    
    // Test VS01 command - Visual Scan status response from radio
    radioCatHandler->parseMessage("VS01;");
    
    // Check that Visual Scan status was set to 1 (ON)
    TEST_ASSERT_EQUAL(1, radioManager->getState().visualScanStatus);
    
    // Test complex VS3 command - should be forwarded to USB
    radioCatHandler->parseMessage("VS30000500000000005050000000051000002;");
    
    // Should have forwarded to USB (assuming AI mode allows it)
    // Note: This depends on the shouldForwardToUSB logic
    tearDown_RadioCATHandler();
}

// Test for PA (Pre-amplifier) command parsing
void test_radioCATHandler_parseRemoteResponse_PA() {
    setUp_RadioCATHandler();
    
    // Test PA1 command - Pre-amplifier ON
    radioCatHandler->parseMessage("PA1;");
    
    // Check that pre-amplifier was set to ON
    TEST_ASSERT_TRUE(radioManager->getState().preAmplifier);
    
    // Test PA0 command - Pre-amplifier OFF
    radioCatHandler->parseMessage("PA0;");
    
    // Check that pre-amplifier was set to OFF
    TEST_ASSERT_FALSE(radioManager->getState().preAmplifier);
    
    tearDown_RadioCATHandler();
}

// Test for FT (VFO selection) command parsing
void test_radioCATHandler_parseRemoteResponse_FT() {
    setUp_RadioCATHandler();
    
    // Test FT0 command - Select VFO A for TX
    radioCatHandler->parseMessage("FT0;");
    
    // Check that TX VFO was set to A (0)
    TEST_ASSERT_EQUAL(0, radioManager->getState().currentTxVfo.load());
    
    // Test FT1 command - Select VFO B for TX
    radioCatHandler->parseMessage("FT1;");
    
    // Check that TX VFO was set to B (1)
    TEST_ASSERT_EQUAL(1, radioManager->getState().currentTxVfo.load());
    
    tearDown_RadioCATHandler();
}

// --- Test Runner ---

extern "C" void run_radiocat_handler_tests() {
    RUN_TEST(test_radioCATHandler_parseRemoteResponse_FA);
    RUN_TEST(test_radioCATHandler_parseRemoteResponse_MD);
    RUN_TEST(test_radioCATHandler_parseRemoteResponse_IF);
    RUN_TEST(test_radioCATHandler_parseRemoteResponse_VS);
    RUN_TEST(test_radioCATHandler_parseRemoteResponse_PA);
    RUN_TEST(test_radioCATHandler_parseRemoteResponse_FT);
}

} // namespace radio
